{
 "title": "Gitlab Runner Fleeting",
 "description": "Prometheus Metrics for Gitlab Runners Fleeting",
 "tags": [ "gitlab" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(fleeting_provisioner_max_instances,job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Errors Total",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (level) (rate(gitlab_runner_errors_total{job=~\"${job:pipe}\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} {{level}}"
    }
   ]
  },
  {
   "title": "Failed Jobs Total",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (failure_reason, job) (rate(gitlab_runner_failed_jobs_total{job=~\"${job:pipe}\"}[$__rate_interval]))",
     "legendFormat": "failure_reason: {{failure_reason}}, job: {{job}}"
    }
   ]
  },
  {
   "title": "Configuration Loads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(gitlab_runner_configuration_loaded_total{job=~\"${job:pipe}\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Configuration Loads Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(gitlab_runner_configuration_loading_error_total{job=~\"${job:pipe}\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Configuration Saved",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(gitlab_runner_configuration_saved_total{job=~\"${job:pipe}\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Configuration Saved Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(gitlab_runner_configuration_saving_error_total{job=~\"${job:pipe}\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Worker Slots",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gitlab_runner_worker_slots_number{job=~\"${job:pipe}\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Runner Concurrent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gitlab_runner_concurrent{job=~\"${job:pipe}\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Job Queuing Duration Exceeded Treshold",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(gitlab_runner_acceptable_job_queuing_duration_exceeded_total{job=~\"${job:pipe}\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Running Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by (executor_stage, job) (gitlab_runner_jobs{job=~\"${job:pipe}\"})",
     "legendFormat": "executor_stage: {{executor_stage}}, job: {{job}}"
    }
   ]
  },
  {
   "title": "Total Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sum by (job) (rate(gitlab_runner_jobs_total{job=~\"${job:pipe}\"}[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Job Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le, controller)(\n    rate(\n      gitlab_runner_job_duration_seconds_bucket{\n        job=~\"${job:pipe}\"\n      }[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le, controller)(\n    rate(\n      gitlab_runner_job_duration_seconds_bucket{\n        job=~\"${job:pipe}\",\n      }[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(\n  0.90,\n  sum by (le, controller)(\n    rate(\n      gitlab_runner_job_duration_seconds_bucket{\n        job=~\"${job:pipe}\"\n      }[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le, controller)(\n    rate(\n      gitlab_runner_job_duration_seconds_bucket{\n        job=~\"${job:pipe}\",\n      }[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "Job  Queue Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le)(\n    rate(\n      gitlab_runner_job_queue_duration_seconds_bucket{\n        job=~\"${job:pipe}\"\n      }[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le)(\n    rate(\n      gitlab_runner_job_queue_duration_seconds_bucket{\n        job=~\"${job:pipe}\",\n      }[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(\n  0.90,\n  sum by (le)(\n    rate(\n      gitlab_runner_job_queue_duration_seconds_bucket{\n        job=~\"${job:pipe}\"\n      }[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le)(\n    rate(\n      gitlab_runner_job_queue_duration_seconds_bucket{\n        job=~\"${job:pipe}\",\n      }[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "50%"
    }
   ]
  },
  { "title": "Worker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Feeds Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by (system_id, runner_name) (rate(gitlab_runner_worker_feeds_total{job=~\"${job:pipe}\"}[$__rate_interval]))",
     "legendFormat": "{{runner_name}}"
    }
   ]
  },
  {
   "title": "Feeds Failures Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum by (runner_name) (rate(gitlab_runner_worker_feed_failures_total{job=~\"${job:pipe}\"}[$__rate_interval]))",
     "legendFormat": "{{runner_name}}"
    }
   ]
  },
  {
   "title": "Processing Failures Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum by (runner_name, failure_type) (rate(gitlab_runner_worker_processing_failures_total{job=~\"${job:pipe}\"}[$__rate_interval]))",
     "legendFormat": "failure_type: {{failure_type}}, runner_name: {{runner_name}}"
    }
   ]
  },
  {
   "title": "Health Check Failures Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum by (runner_name) (rate(gitlab_runner_worker_health_check_failures_total{job=~\"${job:pipe}\"}[$__rate_interval]))",
     "legendFormat": "{{runner_name}}"
    }
   ]
  },
  { "title": "Api and Autoscaling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Api Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum by (endpoint, status, job) (rate(gitlab_runner_api_request_statuses_total{job=~\"${job:pipe}\"}[$__rate_interval]))",
     "legendFormat": "endpoint: {{endpoint}}, status: {{status}}, job: {{job}}"
    }
   ]
  },
  {
   "title": "Api Request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le)(\n    rate(\n      gitlab_runner_api_request_duration_seconds_bucket{\n        job=~\"${job:pipe}\"\n      }[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le)(\n    rate(\n      gitlab_runner_api_request_duration_seconds_bucket{\n        job=~\"${job:pipe}\",\n      }[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(\n  0.90,\n  sum by (le)(\n    rate(\n      gitlab_runner_api_request_duration_seconds_bucket{\n        job=~\"${job:pipe}\"\n      }[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le)(\n    rate(\n      gitlab_runner_api_request_duration_seconds_bucket{\n        job=~\"${job:pipe}\",\n      }[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "Fleeting Instances States",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "sum by (state, runner_name) (fleeting_provisioner_instances{job=~\"${job:pipe}\"})",
     "legendFormat": "state: {{state}}, runner_name: {{runner_name}}"
    }
   ]
  },
  {
   "title": "Fleeting Instance Creation Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le)(\n    rate(\n      fleeting_provisioner_instance_creation_time_seconds_bucket{\n        job=~\"${job:pipe}\"\n      }[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le)(\n    rate(\n      fleeting_provisioner_instance_creation_time_seconds_bucket{\n        job=~\"${job:pipe}\",\n      }[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(\n  0.90,\n  sum by (le)(\n    rate(\n      fleeting_provisioner_instance_creation_time_seconds_bucket{\n        job=~\"${job:pipe}\"\n      }[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le)(\n    rate(\n      fleeting_provisioner_instance_creation_time_seconds_bucket{\n        job=~\"${job:pipe}\",\n      }[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "Fleeting Instance Deleting Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le)(\n    rate(\n      fleeting_provisioner_instance_deletion_time_seconds_bucket{\n        job=~\"${job:pipe}\"\n      }[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le)(\n    rate(\n      fleeting_provisioner_instance_deletion_time_seconds_bucket{\n        job=~\"${job:pipe}\",\n      }[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(\n  0.90,\n  sum by (le)(\n    rate(\n      fleeting_provisioner_instance_deletion_time_seconds_bucket{\n        job=~\"${job:pipe}\"\n      }[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le)(\n    rate(\n      fleeting_provisioner_instance_deletion_time_seconds_bucket{\n        job=~\"${job:pipe}\",\n      }[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "Fleeting Instance Is Running Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le)(\n    rate(\n      fleeting_provisioner_instance_is_running_time_seconds_bucket{\n        job=~\"${job:pipe}\"\n      }[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le)(\n    rate(\n      fleeting_provisioner_instance_is_running_time_seconds_bucket{\n        job=~\"${job:pipe}\",\n      }[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(\n  0.90,\n  sum by (le)(\n    rate(\n      fleeting_provisioner_instance_is_running_time_seconds_bucket{\n        job=~\"${job:pipe}\"\n      }[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le)(\n    rate(\n      fleeting_provisioner_instance_is_running_time_seconds_bucket{\n        job=~\"${job:pipe}\",\n      }[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "50%"
    }
   ]
  },
  {
   "title": "Fleeting Instance Life Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le)(\n    rate(\n      fleeting_provisioner_instance_life_duration_seconds_bucket{\n        job=~\"${job:pipe}\"\n      }[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le)(\n    rate(\n      fleeting_provisioner_instance_life_duration_seconds_bucket{\n        job=~\"${job:pipe}\"\n      }[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(\n  0.90,\n  sum by (le)(\n    rate(\n      fleeting_provisioner_instance_life_duration_seconds_bucket{\n        job=~\"${job:pipe}\"\n      }[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le)(\n    rate(\n      fleeting_provisioner_instance_life_duration_seconds_bucket{\n        job=~\"${job:pipe}\"\n      }[$__rate_interval]\n    )\n  )\n)",
     "legendFormat": "50%"
    }
   ]
  }
 ]
}